@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface Model <<Interface>>
Interface ReadOnlyUserPrefs <<Interface>>
Interface ReadOnlyContactList <<Interface>>
Interface ReadOnlyTaskRecords <<Interface>>

Class ModelManager
Class UserPrefs
Class ContactList
Class TaskRecords

Class UniquePersonList
Class Person

Class TaskList
Class Task
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model
Model .left......> ReadOnlyUserPrefs
Model ..> ReadOnlyContactList
Model .right.> ReadOnlyTaskRecords

ContactList .up.|> ReadOnlyContactList
TaskRecords .up.|> ReadOnlyTaskRecords
UserPrefs .up.|> ReadOnlyUserPrefs

ModelManager .up...|> Model
ModelManager --> "1" ContactList
ModelManager --> "1" UserPrefs
ModelManager --> "1" TaskRecords


ContactList *--> "1" UniquePersonList
UniquePersonList ----> "~* all" Person
TaskRecords -> "1" TaskList
TaskList  --> "~* all" Task

ModelManager ----> "~* filtered" Person
ModelManager -----> "~* filtered" Task

ReadOnlyUserPrefs -right[hidden]- ReadOnlyContactList
ReadOnlyContactList -right[hidden]- ReadOnlyTaskRecords
@enduml
