@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

object task1

object "date1:Date" as d1 {
  date = 2021-07-14
}

object "recurringFrequency1:RecurringFrequency" as r1 {
  recurringFrequency = "week"
}

Class CurrentDate=2021-07-14

task1 --> d1
task1 --> r1

@enduml