@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage{

package "UserPrefs Storage" #F4F6F6{
Interface UserPrefsStorage <<Interface>>
Class JsonUserPrefsStorage
}

Interface Storage <<Interface>>
Class StorageManager


package "TaskRecordsStorage" #F4F6F6{
Interface TaskRecordsStorage <<Interface>>
Class JsonTaskRecordsStorage
Class JsonSerializableTaskRecords
Class JsonAdaptedTask
}

package "ContactListStorage" #F4F6F6{
Interface ContactListStorage <<Interface>>
Class JsonContactListStorage
Class JsonSerializableContactList
Class JsonAdaptedPerson
Class JsonAdaptedGroup
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" ContactListStorage
StorageManager -up-> "1" TaskRecordsStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> ContactListStorage
Storage -down-|> TaskRecordsStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonContactListStorage .up.|> ContactListStorage
JsonContactListStorage ..> JsonSerializableContactList
JsonSerializableContactList --> "*" JsonAdaptedPerson
JsonAdaptedPerson --> JsonAdaptedGroup

JsonTaskRecordsStorage .up.|> TaskRecordsStorage
JsonTaskRecordsStorage ..> JsonSerializableTaskRecords
JsonSerializableTaskRecords --> "*" JsonAdaptedTask

@enduml
